import "./globals.css";
import { Provider, ThemeSwitcher } from "@/components"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <main className="p-2 md:p-6">
            <ThemeSwitcher />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  )
}
